Feat/sdk 259 change meshlod to lod
readyplayerme/rpm-unity-sdk-core pull request #90
Opened 2023-07-20 12:08 UTC by rk132

## [SDK-259](https://ready-player-me.atlassian.net/browse/SDK-259)

## Dependencies
```Package
Avatar Loader: branch
```

## Description

-   pass lod parameter to the avatar loader query instead of meshlod

## Changes

#### Updated

-   pass lod parameter to the avatar loader query instead of meshlod

## How to Test

- Open up test scene for avatar lod
- When changing distance, the LOD is also applied to the head.

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.

2023-07-20 12:48 UTC, HarrisonHough requested changes
Looks good! Just 1 small suggestion in the comments to simplify things a little.

2023-07-20 12:48 UTC, HarrisonHough commented on Tests/Editor/AvatarLoaderTests.cs
> +        private GameObject avatar2;
This is actually not necessary, you can just re-use the same avatar object field, overriding it once you have the vertex count of the first loaded avatar.

2023-07-20 12:58 UTC, HarrisonHough commented on Tests/Editor/AvatarLoaderTests.cs
> +        [UnityTest, CanBeNull]
Also forgot to mention, why was this CanBeNull macro added? 

I believe it's not necessary, and can be removed along with the 
```cs
using JetBrains.Annotations;
```
At the top

2023-07-20 12:58 UTC, rYuuk reviewed
Please can you align the title of PR with our PR formats(you can check the closed PRs). Also for future, regarding branch name, we don't use ticket number in there as it feels redundant.

2023-07-21 07:03 UTC, HarrisonHough approved these changes
Looks good. 
Great stuff!

2023-07-21 09:24 UTC, merged